name: Push
on:
  push:
    branches: [main]
jobs:
  Lint:
    runs-on: ubuntu-latest
    if: |
      (github.repository == 'OpenRG/UN-OG-Training')
      && (github.event.head_commit.message == 'Update UN-OG-Training')
    steps:
      - uses: actions/checkout@v3
      - name: Check formatting
        uses: "lgeiger/black-action@master"
        with:
          args: ". -l 79 --check"
  versioning:
    name: Update versioning
    if: |
      (github.repository == 'OpenRG/UN-OG-Training')
      && !(github.event.head_commit.message == 'Update UN-OG-Training')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.UN_OG_TRAINING_GITHUB }}
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Build changelog
        run: pip install yaml-changelog && make changelog
      - name: Preview changelog update
        run: ".github/get-changelog-diff.sh"
      - name: Update changelog
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          committer_name: Github Actions[bot]
          author_name: Github Actions[bot]
          message: Update UN-OG-Training
          github_token: ${{ secrets.UN_OG_TRAINING_GITHUB }}
  Test:
    runs-on: ${{ matrix.os }}
    if: |
      (github.repository == 'OpenRG/UN-OG-Training')
      && (github.event.head_commit.message == 'Update UN-OG-Training')
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install package
        run: make install
      - name: Test documentation builds
        run: make documentation
      - name: Deploy documentation
        if: matrix.os == 'ubuntu-latest'
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/book/_build/html
  Publish:
    runs-on: ubuntu-latest
    if: |
      (github.repository == 'OpenRG/UN-OG-Training')
      && (github.event.head_commit.message == 'Update UN-OG-Training')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Publish a git tag
        run: ".github/publish-git-tag.sh || true"
